site_name: Sistema de Acompanhamento de Dietas - NoSQL - Daniel Fagundes
site_description: Sistema de banco de dados NoSQL para nutricionistas acompanharem a dieta dos seus pacientes
site_author: Daniel Fagundes
repo_url: https://github.com/DanielPortes/diet-tracking-app
repo_name: diet-tracking-app

theme:
  name: material
  language: pt-BR
  palette:
    primary: teal
    accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

nav:
  - Home: index.md
  - Modelagem de Dados:
    - Visão Geral: modelagem/index.md
    - Modelo de Grafos (Neo4j): modelagem/grafos.md
    - Modelo de Documentos (MongoDB): modelagem/documentos.md
  - Consultas:
    - Neo4j (Cypher): consultas/neo4j.md
    - MongoDB: consultas/mongodb.md
  - Configuração:
    - Instalação: instalacao.md
    - Dumps do Banco: dumps.md