site_name: Sistema de Acompanhamento de Dietas - NoSQL
site_description: Documentação do sistema de bancos de dados NoSQL para acompanhamento de dietas
site_author: AABD
repo_url: https://github.com/seuusuario/diet-tracking-app
repo_name: diet-tracking-app

theme:
  name: material
  palette:
    primary: green
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Instalação e Configuração: instalacao.md
  - Modelagem de Dados:
    - Visão Geral: modelo-dados.md
    - Modelo de Grafos (Neo4j): modelo-neo4j.md
    - Modelo de Documentos (MongoDB): modelo-mongodb.md
  - Consultas:
    - Neo4j (Cypher): consultas-neo4j.md
    - MongoDB: consultas-mongodb.md
  - Guia de Desenvolvimento: desenvolvimento.md

plugins:
  - search